# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


  steps:
    # Ver el contenido del directorio antes de publicarlo
  - script: ls -R $(Build.SourcesDirectory)
    displayName: 'List files in $(Build.SourcesDirectory)'


