trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: listJob
  displayName: 'ListJob'
  pool:
    vmImage: 'ubuntu-latest'
  
  steps:
    # Incluir el template
    - template: azure-pipelines-1.yml  # Nombre de tu archivo template


    # Publicar artefactos directamente
    - publish: $(Build.SourcesDirectory)
      artifact: usd-site-artifact
      displayName: 'Publish artifact'



